#!/usr/bin/env bash
# Display username, user id, and home directory from /etc/passwd using while

while IFS=':' read -r username password uid gid info home shell
do
  echo "$username:$uid:$home"
done < /etc/passwd
