#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code, ordered by occurrences
awk '{print $1, $9}' /tmp/apache-access.log | sort | uniq -c | sort -rn | awk '{printf "%7d %s %s\n", $1, $2, $3}'
