#!/usr/bin/env bash
# Creates PID file, handles signals
echo $$ > /var/run/myscript.pid

clean_up() {
	rm -f /var/run/myscript.pid
	exit
}

trap "echo 'I hate the kill command'; clean_up" SIGTERM
trap "echo 'I hate the kill command'; clean_up" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
